### ISSUE TITLE
Borg-backup mount bug for multiple servers

### ISSUE THREAD

**Issue by stroobl** [fiaasco/borgbackup#22]
As discovered in PR #19 by @noplanman : the borg-backup mount command accepts 3 additional parameters: the name of the backup server, the backup id and the mount path. In the current implementation, the server name is ignored. In case of multiple servers, the backup will always be mounted from the last server in your list.

So: borg-backup mount whatever-you-type-here 20200318-0931 /mnt/
will also mount the backup from the last server in your server list.
This should be fixed.

**Comment by noplanman** [comment]
Wouldn't it make more sense to have the server parameter at the end?
So leaving it away will take the default / last one. Basically: Required parameters first (i.e. backup ID and mount path)

Because at the moment, if only one backup server is defined, it is necessary to add some dummy text as the 2nd parameter, which is a bit weird, as (I assume) most people won't have multiple backup servers.
Or would the idea be, that one "has to" define the second parameter correctly always?

What would the value of the 2nd parameter with multiple backup servers be?
As theoretically, multiple servers can be defined and simply have different pools, so all values (like FQDN, etc.) would be the same.
Would a new `id` field or something need to be added?

**Comment by stroobl** [comment]
I have mixed feelings about this. It feels wrong to put the server name after the mount directory.
On the other hand it's also strange to ignore the server parameter if you only have one backup server. Maybe we should just check for the server name and throw and error if it's incorrect to have consistent behaviour?

**Comment by noplanman** [comment]
If I understand you correctly, the server should always be defined when calling the `mount` command, even if there is only 1 server?

Would an option be to have something like this:
`borg-backup mount <backup-id>[@<backup-server>] <mount-directory>`

If there is no string with `@` it uses the default / last one.

Or does this complicate things?

Alternatively we fix the command as it is now and force the usage of the server.

Also, regarding the last part of my comment, how would we handle multiple backup repos (with different pools) on the same backup server?

**Comment by noplanman** [comment]
Right, I have implemented this on my servers as follows:
Each backup server can have a new `id` field (which doesn't have to be unique), to make the selection via the commands easier, instead of needing the FQDN.

So commands have the following call signatures:
- `borg-backup init [<id|fqdn>]`
- `borg-backup backup [<id|fqdn>]`
- `borg-backup list [<id|fqdn>]`
- `borg-backup check <tag> [<id|fqdn>]`
- `borg-backup info <tag> [<id|fqdn>]`
- `borg-backup mount <tag> <id|fqdn> <mount-path>`

All parameters in `[...]` are optional and will result in querying all servers for the called command if left empty.

Note that I've switched the `backup-tag` and `backup-server` for the `mount` command, to make it consistent with the others.

Examples:
```sh
# ansible config
borgbackup_servers:
  - id: rsync
    fqdn: s010.rsync.net
    ...
  - fqdn: mybackupserver.net
    ...

# commands
# initialise both repos
$ borg-backup init

# backup to s010.rsync.net only
$ borg-backup backup rsync

# list backup tags from all servers
$ borg-backup list

# list backup tags from mybackupserver.net only
$ borg-backup list mybackupserver.net

# check backup 20200404-2000 on rsync
$ borg-backup check 20200404-2000 s010.rsync.net

# get info about backup 20200404-2000 from all servers
$ borg-backup info 20200404-2000

# mount backup 20200404-2000 from rsync to /mnt/borg-repo-mount
$ borg-backup mount 20200404-2000 rsync /mnt/borg-repo-mount
```

Shall I PR my changes?

**Comment by stroobl** [comment]
Looks good and I'm ok to have this in a PR, but I'm trying to get the two other open PRs merged first. Especially 25 will bring much improved testing, what should make it easier to test future PRs. So you might want to hold on for a few days to avoid merge conflicts.

**Comment by noplanman** [comment]
Oh, awesome progress :tada: 

My changes only affect the templates, so there shouldn't be any conflicts.
Will wait anyway, to not have to rebase unnecessarily.
